image: python

stages:
    - build
    - test
    - deploy

build-job: 
    stage: build
    script:
        - pthon3 -V

test-count:
    stage: test
    script:
        - python3 teste.py

deploy-job:
    stage: deploy
    script:
        -echo "terminou :D"
